### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by ofirkris** [PierfrancescoArdino/SGINet#1]
Hi, do you have plans to release code?

**Comment by PierfrancescoArdino** [comment]
Hi, yes. As soon as possible, I just need some time to refactor a bit the code and write down a README

**Comment by jottue** [comment]
Hi, do you have plans to release code (re-implementation of SPG-Net and SGI-Net)?

**Comment by PierfrancescoArdino** [comment]
Hi, the code for SGI-NET is available. I just need to refactor it a bit and wrote the documentation
