### ISSUE TITLE
A question about using a new dataset

### ISSUE THREAD

**Issue by cameron-a-johnson** [PierfrancescoArdino/SGINet#8]
I have been trying to pre-process a new dataset to work with this training pipeline, and after running CPU-only to get a more useful traceback, I'm currently getting errors along these lines:

```
  File "main.py", line 601, in <module>
    train(None, opt)
  File "main.py", line 191, in train
    one_hot_seg_map.scatter_(1, gt_seg_maps, 1)
RuntimeError: index 255 is out of bounds for dimension 1 with size 6
```

Which seems to pertain to issues with index values from the ground truth masks. My guess: the instanceId mask was drawn incorrectly.

For reference: here's what I've tried for preprocessing:

*Add a new train.txt and val.txt* See the existing ones for examples.

*Achieve this structure, for the new dataset:*

```
datasets
├── cityscapes
│   ├── train_img 	
│   │   ├── aachen_000003_000019_leftImg8bit.png
│   │   ├── ... # just the existing image. Easy!
│   ├── val_img		
│   │   ├── frankfurt_000000_000294_leftImg8bit.png
│   │   ├── ...# just the existing image. Easy!
│   ├── train_label	
│   │   ├── aachen_000003_000019_gtFine_trainIds.png
│   │   ├── ... # Draw this. Mask pixel value = class id number.
│   ├── val_label	
│   │   ├── frankfurt_000000_000294_gtFine_trainIds.png
│   │   ├── ... # Draw this. Mask pixel value = class id number.
│   ├── train_inst	
│   │   ├── aachen_000003_000019_gtFine_data.json
│   │   ├── aachen_000003_000019_gtFine_instanceIds.png
│   │   ├── ... # more info below.
│   ├── val_inst	
│   │   ├── frankfurt_000000_000294_gtFine_data.json
│   │   ├── frankfurt_000000_000294_gtFine_instanceIds.png
│   │   ├── ... # more info below.
│   ├── train.txt	
│   ├── val.txt		
```
*gtFine_data.json example: I re-created this. See inline comments.*

```
{
    "26000": { # 26000 = class_id * 1000 + global_id... class 26 should have the next instances named 26001, 26002...
        "class_id": 26,
        "global_id": 0, # this number increments.
        "train_id": 10, # The class_id to train_id is defined in src/datasets/dataset_name.py.
        "area": 293.0,
        "height": 18.0,
        "width": 55.0,
        "box_area": 990.0,
        "area_ratio": 0.295959595959596, # these calculations are straightforward/ adopted from the citsscapesscripts.
        "width_ratio": 37.236363636363635,
        "height_ratio": 56.888888888888886,
        "aspect_ratio": 3.0555555555555554,
        "bbox": [ # captures the pixel bounds of the polygon.
            425.0,
            1158.0,
            442.0,
            1212.0
        ],
        "occlusion": true    # Use a check_occlusion function for this.
    },
```

*Drawing _gtFine_instanceIds.png:*

You need to draw these too in preprcessing. They're like the "trainId" masks, but each object instance should have a unique mask value. So those are created by multiplying the "class_id" by 1000, then incrementing for unique objects. So 3 objects with class_id "5" will have mask pixel values 5000, 5001, 5002.

(I defined class_id to equal train_id, like you did I guess for idd.)

*src/datasets:*
Next, you can create a new src/datasets/myNewDataset.py. For a new semantic segmentation dataset, it can be like the cityscapes dataset definition in src/datasets/, but you'll need to change a couple things, most importantly this snippet, particularly `self.ch_to_inst_id`:
```
        if self.opt.label_nc == 8:
            self.ch_to_inst_id = {"5":"24", "6":"26"}
            self.param_obj = {"24": [0.25, 50, 10, 4, 0.4],
                              "26": [0.4, 50, 20, 6, 0.5]}
        elif self.opt.label_nc == 17:
            self.ch_to_inst_id = {"8": "24", "9": "25", "10": "26","11": "27", "12": "28", "13": "31", "14":"32", "15":"33"}
            self.param_obj = {"24": [0.25, 50, 10, 4, 0.3],
                              "25": [0.1, 50, 10, 10, 0.10],
                              "26": [0.6, 40, 10, 1.5, 0.70],
                              "27": [0.5, 30, 10, 3, 0.4],
                              "28": [0.5, 50, 20, 6, 0.5],
                              "31": [0.5, 50, 20, 6, 0.5],
                              "32": [0.20, 50, 10, 6, 0.25],
                              "33": [0.20, 50, 10, 6, 0.25],
                              }
```

As mentioned, The new dataset's is defined simply like this:
```
            self.ch_to_inst_id = {"1": "1", "2": "2", "3": "3", "4": "4"...
```

*Running main.py* :
Finally, create a new "script/" file with preferred parameters.

So that might be it, as far as I know, but the indexing problem in main.py implies that I've done something wrong. Can you think of any obvious step that I'm missing, Pierfrancesco? 

Thanks for reading! :)

**Comment by cameron-a-johnson** [comment]
Reference on instanceId drawing:
https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/json2instanceImg.py#L13

**Comment by cameron-a-johnson** [comment]
Update: I have this working now. The above error was a bug in mask drawing. Also, editing in a step I left out of the above for implementing a new dataset: creating a version of `labels.py` for the new dataset's labels.

**Comment by PierfrancescoArdino** [comment]
Can I close the issue?

**Comment by cameron-a-johnson** [comment]
Yes, thanks.
